// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Clean_CaDET.View
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidClean_CaDETPackageString = "549a40ba-7800-435f-8e0f-b0c5ec49fbf3";
        public static Guid guidClean_CaDETPackage = new Guid(guidClean_CaDETPackageString);

        public const string guidClean_CaDETPackageCmdSetString = "e950531b-e655-48b1-8c63-ac3526bdbb54";
        public static Guid guidClean_CaDETPackageCmdSet = new Guid(guidClean_CaDETPackageCmdSetString);

        public const string guidImagesString = "ec7304be-ae7a-4fe7-83d7-ef2a19d26720";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopLevelMenu = 0x1021;
        public const int MenuGroup = 0x1020;
        public const int TutoringWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}