// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Clean_CaDET
{
    internal sealed partial class Vsix
    {
        public const string Id = "Clean_CaDET.995f2c75-ae45-4bfe-8752-fe7e747781ea";
        public const string Name = "Clean CaDET";
        public const string Description = @"TODO";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "nikola.luburic@uns.ac.rs";
        public const string Tags = "";
    }
}
